name: env_simba
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adjusttext=1.3.0
  - anndata=0.11.1
  - array-api-compat=1.10.0
  - attrs=24.3.0
  - bedtools=2.31.1
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - exceptiongroup=1.2.2
  - filelock=3.16.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h5py=3.12.1
  - hdf5=1.14.4
  - jinja2=3.1.5
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - kneed=0.8.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtorch=2.3.1
  - libuv=1.48.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - llvmlite=0.43.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - numba=0.60.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.1.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pybedtools=0.11.0
  - pynndescent=0.5.13
  - pyparsing=3.2.1
  - pysam=0.22.1
  - pytables=3.10.2
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytorch=2.3.1
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.6.0
  - scikit-misc=0.1.4
  - scipy=1.15.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.6.0
  - simba=1.2
  - simba_pbg=1.2
  - six=1.17.0
  - sleef=3.7
  - snappy=1.2.1
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tbb=2022.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.2.3
  - zstd=1.5.6
  - pip:
    - aiobotocore==2.5.4
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aioitertools==0.12.0
    - aiosignal==1.3.2
    - appnope==0.1.4
    - asciitree==0.3.3
    - asttokens==3.0.0
    - botocore==1.31.17
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cloudpickle==3.1.0
    - colorcet==3.1.0
    - comm==0.2.2
    - dask==2024.12.1
    - dask-expr==1.1.21
    - dask-image==2024.5.3
    - datashader==0.16.3
    - debugpy==1.8.11
    - decorator==5.1.1
    - distributed==2024.12.1
    - docrep==0.3.2
    - executing==2.1.0
    - fasteners==0.19
    - fastjsonschema==2.21.1
    - frozenlist==1.5.0
    - fsspec==2023.6.0
    - geopandas==1.0.1
    - idna==3.10
    - igraph==0.11.8
    - imageio==2.36.1
    - importlib-metadata==8.5.0
    - inflect==7.5.0
    - ipykernel==6.29.5
    - ipython==8.31.0
    - jedi==0.19.2
    - jmespath==1.0.1
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - lazy-loader==0.4
    - legacy-api-wrap==1.4.1
    - leidenalg==0.10.2
    - locket==1.0.0
    - markdown-it-py==3.0.0
    - matplotlib-inline==0.1.7
    - matplotlib-scalebar==0.8.1
    - mdurl==0.1.2
    - more-itertools==10.5.0
    - msgpack==1.1.0
    - multidict==6.1.0
    - multipledispatch==1.0.0
    - multiscale-spatial-image==1.0.1
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - numcodecs==0.14.1
    - ome-zarr==0.10.3
    - omnipath==1.0.8
    - param==2.2.0
    - parso==0.8.4
    - partd==1.4.2
    - pexpect==4.9.0
    - pims==0.7
    - platformdirs==4.3.6
    - plotly==5.24.1
    - pooch==1.8.2
    - prompt-toolkit==3.0.48
    - propcache==0.2.1
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==18.1.0
    - pyct==0.5.0
    - pygments==2.19.1
    - pyogrio==0.10.0
    - pyproj==3.7.0
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - referencing==0.35.1
    - requests==2.32.3
    - rich==13.9.4
    - rpds-py==0.22.3
    - s3fs==2023.6.0
    - scanpy==1.10.4
    - scikit-image==0.25.0
    - session-info==1.0.0
    - shapely==2.0.6
    - slicerator==1.1.0
    - sortedcontainers==2.4.0
    - spatial-image==1.1.0
    - spatialdata==0.2.5.post0
    - squidpy==1.6.2
    - stack-data==0.6.3
    - stdlib-list==0.11.0
    - tblib==3.0.0
    - tenacity==9.0.0
    - texttable==1.7.0
    - tifffile==2024.12.12
    - toolz==1.0.0
    - tornado==6.4.2
    - traitlets==5.14.3
    - typeguard==4.4.1
    - urllib3==1.26.20
    - validators==0.34.0
    - wcwidth==0.2.13
    - wrapt==1.17.0
    - xarray==2024.7.0
    - xarray-dataclasses==1.9.1
    - xarray-datatree==0.0.15
    - xarray-schema==0.0.3
    - xarray-spatial==0.4.0
    - yarl==1.18.3
    - zarr==2.18.3
    - zict==3.0.0
    - zipp==3.21.0
